import type { Address, Hex } from 'viem';
import type { LpRelease } from '../lp-release.mjs';
export const ENS_CHAIN_ID: 11155111;
export const RELEASE_KEY: string;
export const REGISTRAR_KEY: string;
export const ALL_ROLES: bigint;
export const SET_TEXT_ROLE: bigint;
export const NAME_ROLES: bigint;
export type ReleasePointer = { schema: 'pintool-ens-release-v1'; chainId: 11155111; provider: Address; releaseId: string; version: number; publicationDigest: Hex };
export type EnsSelection = { name: string; node: Hex; pointer: ReleasePointer };
export function normalizeRoot(value: string): string;
export function normalizeLabel(value: string): string;
export function strategyName(value: string, root: string): string;
export function parseReleasePointer(value: unknown): ReleasePointer;
export function releasePointer(release: LpRelease, digest: string): ReleasePointer;
export function parseSelection(value: unknown, root: string): EnsSelection;
export function publicReleaseHash(release: LpRelease): Hex;
export function manifestMessage(name: string, root: string, release: LpRelease, digest: string): string;
export function textResource(node: Hex, key: string): bigint;
